spring.application.name=farmacia-spring-boot
server.port=8081

spring.datasource.url=jdbc:sqlserver://DESKTOP-C2NC88E:1433;databaseName=BoticaDB2026;encrypt=true;trustServerCertificate=true
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_PASSWORD
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.thymeleaf.cache=false
server.error.include-message=always
